# Generated by Django 5.0.2 on 2024-03-04 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_person_birthday_alter_person_birthtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('addres', models.CharField(max_length=60)),
                ('mobail', models.CharField(max_length=60)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.person')),
            ],
        ),
    ]
