# Generated by Django 5.0.2 on 2024-03-04 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.person'),
        ),
    ]
