# Generated by Django 5.0.2 on 2024-03-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.person'),
        ),
    ]
