# Generated by Django 5.0.2 on 2024-03-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_parents_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
